/**
 * Local control channel: lets the `munder` CLI (or any loopback caller with
 * the boot token) inspect and drive the LIVE app without touching its windows.
 *
 * Mirrors the Slack reply endpoint (src/main/index.ts startSlackReplyServer +
 * SlackReplyServer in slack.ts) on purpose: loopback-only HTTP, per-boot
 * random token, `{ port, token }` published to a 0600 file in userData, and
 * best-effort idempotent stop. M0 serves read-only health (`GET /salud`);
 * session routes arrive in M1/M2 on this same server and auth.
 *
 * Deliberately electron-free (node:http only) so the focused tests can bind
 * a real server headlessly via test/load-ts.cjs, like the broker does.
 */
import { createServer, type IncomingMessage, type Server, type ServerResponse } from 'node:http';

export interface ControlChannelOptions {
  /** Per-boot secret. Generated by the caller (randomBytes), never logged. */
  token: string;
}

function isLoopback(addr: string): boolean {
  const a = addr.replace(/^::ffff:/, '');
  return a === '::1' || a.startsWith('127.');
}

function json(res: ServerResponse, status: number, body: unknown): void {
  const text = JSON.stringify(body);
  res.writeHead(status, { 'content-type': 'application/json', 'content-length': Buffer.byteLength(text) });
  res.end(text);
}

export class ControlChannel {
  private server: Server | null = null;
  private readonly token: string;

  constructor(opts: ControlChannelOptions) {
    this.token = opts.token;
  }

  /** Bind a loopback port (0 ⇒ OS-assigned). Resolves the actual bound port. */
  start(preferredPort = 0): Promise<{ ok: boolean; port?: number; error?: string }> {
    return new Promise((resolve) => {
      if (this.server) { resolve({ ok: false, error: 'already running' }); return; }
      const server = createServer((req, res) => this.handle(req, res));
      const onError = (e: Error): void => {
        server.off('listening', onListening);
        resolve({ ok: false, error: e instanceof Error ? e.message : String(e) });
      };
      const onListening = (): void => {
        server.off('error', onError);
        this.server = server;
        const addr = server.address();
        resolve({ ok: true, port: addr && typeof addr === 'object' ? addr.port : preferredPort });
      };
      server.once('error', onError);
      server.once('listening', onListening);
      // '127.0.0.1' ONLY — never tunneled, never public. The token is a second
      // layer, not the boundary: a non-loopback peer is refused before auth.
      server.listen(preferredPort, '127.0.0.1');
    });
  }

  /** Close the endpoint. Idempotent and best-effort. */
  stop(): void {
    try { this.server?.close(); } catch { /* noop */ }
    this.server = null;
  }

  /** Bound port, or null when stopped. For logs only — callers read the file. */
  port(): number | null {
    if (!this.server) return null;
    const addr = this.server.address();
    return addr && typeof addr === 'object' ? addr.port : null;
  }

  private authorized(req: IncomingMessage): boolean {
    const header = req.headers.authorization ?? '';
    return header === `Bearer ${this.token}`;
  }

  private handle(req: IncomingMessage, res: ServerResponse): void {
    // Defense in depth: even bound loopback-only, refuse any non-loopback peer.
    if (!isLoopback(req.socket.remoteAddress ?? '')) {
      json(res, 403, { ok: false, error: 'loopback only' });
      return;
    }
    const path = (req.url ?? '').split('?')[0];
    if (req.method === 'GET' && path === '/salud') {
      if (!this.authorized(req)) {
        json(res, 401, { ok: false, error: 'unauthorized' });
        return;
      }
      json(res, 200, { ok: true, service: 'munder-control' });
      return;
    }
    json(res, 404, { ok: false, error: 'not found' });
  }
}
