/**
 * Local control channel: lets the `munder` CLI (or any loopback caller with
 * the boot token) inspect and drive the LIVE app without touching its windows.
 *
 * Mirrors the Slack reply endpoint (src/main/index.ts startSlackReplyServer +
 * SlackReplyServer in slack.ts) on purpose: loopback-only HTTP, per-boot
 * random token, `{ port, token }` published to a 0600 file in userData, and
 * best-effort idempotent stop. M0 serves read-only health (`GET /salud`);
 * session routes arrive in M1/M2 on this same server and auth.
 *
 * Deliberately electron-free (node:http only) so the focused tests can bind
 * a real server headlessly via test/load-ts.cjs, like the broker does.
 */
import { createServer, type IncomingMessage, type Server, type ServerResponse } from 'node:http';
import { tokenizeCommand } from '../shared/commandLine';

export interface ControlChannelOptions {
  /** Per-boot secret. Generated by the caller (randomBytes), never logged. */
  token: string;
  /** Spawn delegate (M2). Absent in M0 builds → session routes answer 501. */
  spawn?: ChannelSpawnFn;
  /** Kill delegate (M2). Same 501 rule. */
  kill?: ChannelKillFn;
  /** Session read delegate (M1): registry + live PTYs merged. Absent → 501. */
  read?: SessionReaderFn;
  /** Repaint broadcast delegate (M3): tells every live window to repaint its
   *  canvases. Returns the window count reached. Absent → 501. */
  repaint?: () => number;
}

/** Subset of SpawnOptions the channel accepts — the same fields the renderer
 *  sends `pty:spawn` after assembling them (AddAgentModal precedent); main
 *  passes them straight to `spawnAgentCore`, which owns inference, the
 *  missing-CLI installer, worktree isolation and hive provisioning. */
export interface ChannelSpawnOpts {
  id: string;
  cwd: string;
  command: string;
  provider?: string;
  args?: string[];
  cols?: number;
  rows?: number;
  isolate?: boolean;
  hive?: { id: string; name: string; provider?: string; cwd: string; role?: string; capabilities?: string[] };
}

export type ChannelSpawnFn = (opts: ChannelSpawnOpts) => Promise<{
  ok: boolean; error?: string; cwd?: string; worktreePath?: string; resumed?: boolean; seedPrompt?: string;
}> | { ok: boolean; error?: string; cwd?: string; worktreePath?: string; resumed?: boolean; seedPrompt?: string };

export type ChannelKillFn = (id: string) =>
  | { ok: boolean; error?: string }
  | Promise<{ ok: boolean; error?: string }>;

/** Registry-side agent facts (subset of RegistryAgent used for display). */
export interface RegistryAgentView {
  id: string;
  name: string;
  provider?: string;
  role?: string;
  cwd?: string;
}

/** Live PTY facts (subset of ptyManager.list()). */
export interface PtyView {
  id: string;
  cwd: string;
  command: string;
  pid: number;
}

/** One row of `sesion ver`: registry identity + liveness. */
export interface SessionAgentView {
  id: string;
  name: string;
  provider?: string;
  role?: string;
  cwd?: string;
  live: boolean;
  pid?: number;
}

export type SessionReaderFn = () =>
  | { agents: SessionAgentView[] }
  | Promise<{ agents: SessionAgentView[] }>;

/**
 * Join registry identity with PTY liveness. Pure: `pty-<id>` links a live PTY
 * to its agent (the convention AddAgentModal establishes); PTYs with no
 * registry entry (orphans, pre-registry spawns) show as live unknowns rather
 * than vanishing. NOTE: no `model` column — models live renderer-side (store
 * + spawn args), not in the registry; M6 handles model selection at build.
 */
export function buildSessionView(
  ptyList: PtyView[],
  registryAgents: Record<string, RegistryAgentView>
): SessionAgentView[] {
  const out: SessionAgentView[] = [];
  for (const [id, meta] of Object.entries(registryAgents)) {
    const live = ptyList.find((p) => p.id === `pty-${id}`);
    out.push({
      id,
      name: meta.name ?? id,
      provider: meta.provider,
      role: meta.role,
      cwd: meta.cwd,
      live: !!live,
      pid: live?.pid,
    });
  }
  for (const p of ptyList) {
    const known = Object.keys(registryAgents).some((id) => `pty-${id}` === p.id);
    // Keys always present (undefined, never absent): the JSON wire format is
    // identical either way, but explicit shape keeps deepEqual/tests honest.
    if (!known) out.push({ id: p.id, name: p.id, provider: undefined, role: undefined, cwd: p.cwd, live: true, pid: p.pid });
  }
  return out;
}

/** User-facing agent description (CLI `sesion armar`) → spawn opts. Pure. */
export interface AgentSpec {
  name?: unknown;
  cwd?: unknown;
  command?: unknown;
  provider?: unknown;
  role?: unknown;
  capabilities?: unknown;
  isolate?: unknown;
}

/** Validate exactly like the UI hire path (name/cwd/command required). Pure. */
export function validateAgentSpec(spec: AgentSpec): { ok: true } | { ok: false; error: string } {
  if (!spec || typeof spec !== 'object') return { ok: false, error: 'spec inválida' };
  if (typeof spec.name !== 'string' || !spec.name.trim()) return { ok: false, error: 'falta el nombre del agente' };
  if (typeof spec.cwd !== 'string' || !spec.cwd.trim()) return { ok: false, error: 'falta la carpeta de trabajo (cwd)' };
  if (typeof spec.command !== 'string' || !spec.command.trim()) return { ok: false, error: 'falta el comando (p. ej. "claude --model opus")' };
  if (spec.provider !== undefined && (typeof spec.provider !== 'string' || !spec.provider.trim())) {
    return { ok: false, error: 'proveedor inválido' };
  }
  if (spec.role !== undefined && typeof spec.role !== 'string') return { ok: false, error: 'rol inválido' };
  if (spec.capabilities !== undefined &&
    (!Array.isArray(spec.capabilities) || spec.capabilities.some((c) => typeof c !== 'string'))) {
    return { ok: false, error: 'capabilities debe ser lista de strings' };
  }
  return { ok: true };
}

/** Agent id scheme, mirroring AddAgentModal.uniqueId (slug + timestamp). Pure. */
export function uniqueAgentId(name: string): string {
  return `${name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'agent'}-${Date.now().toString(36)}`;
}

/** Build spawn opts from a validated spec. Pure (tokenizeCommand is shared). */
export function buildChannelSpawnOpts(spec: {
  name: string; cwd: string; command: string; provider?: string;
  role?: string; capabilities?: string[]; isolate?: boolean;
}): { ptyId: string; id: string; opts: ChannelSpawnOpts } {
  const id = uniqueAgentId(spec.name);
  const ptyId = `pty-${id}`;
  const [exe, ...args] = tokenizeCommand(spec.command.trim());
  return {
    id,
    ptyId,
    opts: {
      id: ptyId,
      cwd: spec.cwd,
      command: exe,
      provider: spec.provider,
      args,
      cols: 100,
      rows: 30,
      isolate: spec.isolate,
      hive: {
        id,
        name: spec.name.trim(),
        provider: spec.provider,
        cwd: spec.cwd,
        role: spec.role?.trim() || undefined,
        capabilities: spec.capabilities
      }
    }
  };
}

function isLoopback(addr: string): boolean {
  const a = addr.replace(/^::ffff:/, '');
  return a === '::1' || a.startsWith('127.');
}

function json(res: ServerResponse, status: number, body: unknown): void {
  const text = JSON.stringify(body);
  res.writeHead(status, { 'content-type': 'application/json', 'content-length': Buffer.byteLength(text) });
  res.end(text);
}

/** Max JSON body we will buffer (mirrors the broker's payload cap idea). */
const MAX_JSON_BODY = 65536;

function readJsonBody(req: IncomingMessage): Promise<{ ok: true; value: unknown } | { ok: false; error: string }> {
  return new Promise((resolve) => {
    const chunks: Buffer[] = [];
    let size = 0;
    let done = false;
    const fail = (error: string): void => {
      if (done) return;
      done = true;
      resolve({ ok: false, error });
    };
    req.on('data', (c: Buffer) => {
      size += c.length;
      if (size > MAX_JSON_BODY) {
        fail('payload_too_large');
        try { req.destroy(); } catch { /* noop */ }
        return;
      }
      chunks.push(c);
    });
    req.on('end', () => {
      if (done) return;
      done = true;
      try {
        resolve({ ok: true, value: JSON.parse(Buffer.concat(chunks).toString('utf8')) });
      } catch {
        resolve({ ok: false, error: 'invalid_json' });
      }
    });
    req.on('error', () => fail('body_error'));
  });
}

export class ControlChannel {
  private server: Server | null = null;
  private readonly token: string;
  private readonly spawn?: ChannelSpawnFn;
  private readonly kill?: ChannelKillFn;
  private readonly repaint?: () => number;
  private readonly read?: SessionReaderFn;

  constructor(opts: ControlChannelOptions) {
    this.token = opts.token;
    this.spawn = opts.spawn;
    this.kill = opts.kill;
    this.repaint = opts.repaint;
    this.read = opts.read;
  }

  /** Bind a loopback port (0 ⇒ OS-assigned). Resolves the actual bound port. */
  start(preferredPort = 0): Promise<{ ok: boolean; port?: number; error?: string }> {
    return new Promise((resolve) => {
      if (this.server) { resolve({ ok: false, error: 'already running' }); return; }
      const server = createServer((req, res) => {
        void this.handle(req, res).catch(() => {
          try { json(res, 500, { ok: false, error: 'internal' }); } catch { /* socket gone */ }
        });
      });
      const onError = (e: Error): void => {
        server.off('listening', onListening);
        resolve({ ok: false, error: e instanceof Error ? e.message : String(e) });
      };
      const onListening = (): void => {
        server.off('error', onError);
        this.server = server;
        const addr = server.address();
        resolve({ ok: true, port: addr && typeof addr === 'object' ? addr.port : preferredPort });
      };
      server.once('error', onError);
      server.once('listening', onListening);
      // '127.0.0.1' ONLY — never tunneled, never public. The token is a second
      // layer, not the boundary: a non-loopback peer is refused before auth.
      server.listen(preferredPort, '127.0.0.1');
    });
  }

  /** Close the endpoint. Idempotent and best-effort. */
  stop(): void {
    try { this.server?.close(); } catch { /* noop */ }
    this.server = null;
  }

  /** Bound port, or null when stopped. For logs only — callers read the file. */
  port(): number | null {
    if (!this.server) return null;
    const addr = this.server.address();
    return addr && typeof addr === 'object' ? addr.port : null;
  }

  private authorized(req: IncomingMessage): boolean {
    const header = req.headers.authorization ?? '';
    return header === `Bearer ${this.token}`;
  }

  private async handle(req: IncomingMessage, res: ServerResponse): Promise<void> {
    // Defense in depth: even bound loopback-only, refuse any non-loopback peer.
    if (!isLoopback(req.socket.remoteAddress ?? '')) {
      json(res, 403, { ok: false, error: 'loopback only' });
      return;
    }
    const path = (req.url ?? '').split('?')[0];
    if (req.method === 'GET' && path === '/salud') {
      if (!this.authorized(req)) {
        json(res, 401, { ok: false, error: 'unauthorized' });
        return;
      }
      json(res, 200, { ok: true, service: 'munder-control' });
      return;
    }
    if (req.method === 'GET' && path === '/sesion') {
      if (!this.authorized(req)) {
        json(res, 401, { ok: false, error: 'unauthorized' });
        return;
      }
      if (!this.read) {
        json(res, 501, { ok: false, error: 'lectura no disponible en este build' });
        return;
      }
      try {
        const snap = await this.read();
        const agents = Array.isArray(snap?.agents) ? snap.agents : [];
        json(res, 200, { ok: true, agents, count: agents.length });
      } catch (e: unknown) {
        json(res, 500, { ok: false, error: e instanceof Error ? e.message : String(e) });
      }
      return;
    }
    if ((req.method === 'POST' && path === '/sesion/agentes') ||
        (req.method === 'DELETE' && path.startsWith('/sesion/agentes/'))) {
      if (!this.authorized(req)) {
        json(res, 401, { ok: false, error: 'unauthorized' });
        return;
      }
      void this.handleMutation(req, res, path).catch((e: unknown) => {
        json(res, 500, { ok: false, error: e instanceof Error ? e.message : String(e) });
      });
      return;
    }
    if (req.method === 'POST' && path === '/repaint') {
      if (!this.authorized(req)) {
        json(res, 401, { ok: false, error: 'unauthorized' });
        return;
      }
      if (!this.repaint) {
        json(res, 501, { ok: false, error: 'repaint no disponible en este build' });
        return;
      }
      try {
        const windows = this.repaint();
        json(res, 200, { ok: true, windows });
      } catch (e: unknown) {
        json(res, 500, { ok: false, error: e instanceof Error ? e.message : String(e) });
      }
      return;
    }
    json(res, 404, { ok: false, error: 'not found' });
  }

  private async handleMutation(req: IncomingMessage, res: ServerResponse, path: string): Promise<void> {
    if (req.method === 'POST') {
      if (!this.spawn) {
        json(res, 501, { ok: false, error: 'spawn no disponible en este build' });
        return;
      }
      const body = await readJsonBody(req);
      if (!body.ok) {
        json(res, body.error === 'payload_too_large' ? 413 : 400, { ok: false, error: body.error });
        return;
      }
      const spec = (body.value ?? {}) as AgentSpec;
      const valid = validateAgentSpec(spec);
      if (!valid.ok) {
        json(res, 400, { ok: false, error: valid.error });
        return;
      }
      const v = spec as { name: string; cwd: string; command: string; provider?: string; role?: string; capabilities?: string[]; isolate?: boolean };
      const built = buildChannelSpawnOpts({
        name: v.name, cwd: v.cwd, command: v.command, provider: v.provider,
        role: v.role, capabilities: v.capabilities, isolate: v.isolate
      });
      const r = await this.spawn(built.opts);
      if (!r.ok) {
        // Same contract as pty:spawn: accepted-but-failed rides 200 + ok:false.
        json(res, 200, { ok: false, error: r.error ?? 'spawn failed' });
        return;
      }
      json(res, 200, {
        ok: true, id: built.id, ptyId: built.ptyId,
        cwd: r.cwd, worktreePath: r.worktreePath, provider: v.provider
      });
      return;
    }
    // DELETE /sesion/agentes/:id
    if (!this.kill) {
      json(res, 501, { ok: false, error: 'kill no disponible en este build' });
      return;
    }
    const id = decodeURIComponent(path.slice('/sesion/agentes/'.length)).trim();
    if (!id || id.includes('/')) {
      json(res, 400, { ok: false, error: 'id inválido' });
      return;
    }
    const r = await this.kill(id);
    if (!r.ok) {
      json(res, 404, { ok: false, error: r.error ?? 'no existe' });
      return;
    }
    json(res, 200, { ok: true, id });
  }
}
