/**
 * Local control channel: lets the `munder` CLI (or any loopback caller with
 * the boot token) inspect and drive the LIVE app without touching its windows.
 *
 * Mirrors the Slack reply endpoint (src/main/index.ts startSlackReplyServer +
 * SlackReplyServer in slack.ts) on purpose: loopback-only HTTP, per-boot
 * random token, `{ port, token }` published to a 0600 file in userData, and
 * best-effort idempotent stop. M0 serves read-only health (`GET /salud`);
 * session routes arrive in M1/M2 on this same server and auth.
 *
 * Deliberately electron-free (node:http only) so the focused tests can bind
 * a real server headlessly via test/load-ts.cjs, like the broker does.
 */
import { createServer, type IncomingMessage, type Server, type ServerResponse } from 'node:http';
import { tokenizeCommand } from '../shared/commandLine';
import type { OfficePack } from '../shared/officePack';
import { packAgentName, packBrief } from '../shared/packBrief';

export interface ControlChannelOptions {
  /** Per-boot secret. Generated by the caller (randomBytes), never logged. */
  token: string;
  /** Spawn delegate (M2). Absent in M0 builds → session routes answer 501. */
  spawn?: ChannelSpawnFn;
  /** Kill delegate (M2). Same 501 rule. */
  kill?: ChannelKillFn;
  /** Session read delegate (M1): registry + live PTYs merged. Absent → 501. */
  read?: SessionReaderFn;
  /** Repaint broadcast delegate (M3): tells every live window to repaint its
   *  canvases. Returns the window count reached. Absent → 501. */
  repaint?: () => number;
  /** Office Packs (bundled, core merged in). Absent → pack routes answer 501. */
  packs?: () => { packs: OfficePack[] };
  /** Validate a pack that arrived from outside (a file): outward levels capped at 'ask'. */
  importPack?: (raw: unknown) => { pack?: OfficePack; errors: string[] };
  /** Deliver a job brief to a freshly spawned agent's inbox (from god). */
  brief?: (agentId: string, subject: string, body: string) => void;
  /** Who is answering `GET /salud`: the main pid, the app version and the
   *  office identity. The Reviver (tools/munder/lib-reviver.cjs) needs them to
   *  tell "this office is healthy" from "some Munder answered". Absent → the
   *  plain M0 answer. */
  about?: () => InstanceInfo;
}

/** What `GET /salud` adds when `about` is set. Nothing secret: no token, no key. */
export interface InstanceInfo {
  pid: number;
  version: string;
  /** Link office id (public fingerprint of the office key), or null if this office never made one. */
  office_id: string | null;
  started_at: string;
}

/** One pack as `GET /packs` lists it: enough to choose, nothing more. */
export interface PackSummary {
  id: string;
  name: string;
  tagline: string;
  agents: Array<{ id: string; name: string; role: string; summary: string; default: boolean }>;
}

export function summarizePack(p: OfficePack): PackSummary {
  const picks = new Set(p.defaultPicks);
  return {
    id: p.businessType,
    name: p.displayName,
    tagline: p.tagline,
    agents: p.agents.map((a) => ({ id: a.id, name: packAgentName(a), role: a.role, summary: a.summary, default: picks.has(a.id) }))
  };
}

/** `POST /sesion/pack` body. `pack` is a bundled id; `packJson` is an imported pack. */
export interface PackSessionRequest {
  pack?: unknown;
  packJson?: unknown;
  cwd?: unknown;
  command?: unknown;
  provider?: unknown;
  /** Agent ids to start; defaults to the pack's defaultPicks. */
  picks?: unknown;
}

/** Resolve which agents of which pack to start. Pure (the loaders are injected). */
export function planPackSession(
  req: PackSessionRequest,
  deps: { packs: () => { packs: OfficePack[] }; importPack?: (raw: unknown) => { pack?: OfficePack; errors: string[] } }
): { ok: true; pack: OfficePack; imported: boolean; agents: OfficePack['agents']; cwd: string; command: string; provider?: string }
  | { ok: false; error: string } {
  if (typeof req.cwd !== 'string' || !req.cwd.trim()) return { ok: false, error: 'falta la carpeta de trabajo (cwd)' };
  if (typeof req.command !== 'string' || !req.command.trim()) return { ok: false, error: 'falta el comando (p. ej. "claude")' };
  if (req.provider !== undefined && (typeof req.provider !== 'string' || !req.provider.trim())) return { ok: false, error: 'proveedor inválido' };
  let pack: OfficePack | undefined;
  let imported = false;
  if (req.packJson !== undefined) {
    if (!deps.importPack) return { ok: false, error: 'importar packs no está disponible en este build' };
    const r = deps.importPack(req.packJson);
    if (!r.pack) return { ok: false, error: `pack inválido: ${r.errors.join('; ') || 'sin detalle'}` };
    pack = r.pack;
    imported = true;
  } else if (typeof req.pack === 'string' && req.pack.trim()) {
    pack = deps.packs().packs.find((p) => p.businessType === (req.pack as string).trim());
    if (!pack) return { ok: false, error: `no existe el pack «${req.pack}» (munder sesion packs los lista)` };
  } else {
    return { ok: false, error: 'falta el pack (id o packJson)' };
  }
  let ids: string[];
  if (req.picks === undefined) ids = pack.defaultPicks;
  else if (Array.isArray(req.picks) && req.picks.every((x) => typeof x === 'string')) ids = req.picks as string[];
  else return { ok: false, error: 'picks debe ser lista de ids' };
  const unknown = ids.filter((id) => !pack!.agents.some((a) => a.id === id));
  if (unknown.length) return { ok: false, error: `el pack no tiene: ${unknown.join(', ')}` };
  const agents = pack.agents.filter((a) => ids.includes(a.id));
  if (!agents.length) return { ok: false, error: 'ningún agente elegido' };
  return {
    ok: true, pack, imported, agents,
    cwd: req.cwd.trim(), command: req.command.trim(),
    provider: typeof req.provider === 'string' ? req.provider.trim() : undefined
  };
}

/** Subset of SpawnOptions the channel accepts — the same fields the renderer
 *  sends `pty:spawn` after assembling them (AddAgentModal precedent); main
 *  passes them straight to `spawnAgentCore`, which owns inference, the
 *  missing-CLI installer, worktree isolation and hive provisioning. */
export interface ChannelSpawnOpts {
  id: string;
  cwd: string;
  command: string;
  provider?: string;
  args?: string[];
  cols?: number;
  rows?: number;
  isolate?: boolean;
  hive?: { id: string; name: string; provider?: string; cwd: string; role?: string; capabilities?: string[] };
}

export type ChannelSpawnFn = (opts: ChannelSpawnOpts) => Promise<{
  ok: boolean; error?: string; cwd?: string; worktreePath?: string; resumed?: boolean; seedPrompt?: string;
}> | { ok: boolean; error?: string; cwd?: string; worktreePath?: string; resumed?: boolean; seedPrompt?: string };

export type ChannelKillFn = (id: string) =>
  | { ok: boolean; error?: string }
  | Promise<{ ok: boolean; error?: string }>;

/** Registry-side agent facts (subset of RegistryAgent used for display). */
export interface RegistryAgentView {
  id: string;
  name: string;
  provider?: string;
  role?: string;
  cwd?: string;
}

/** Live PTY facts (subset of ptyManager.list()). */
export interface PtyView {
  id: string;
  cwd: string;
  command: string;
  pid: number;
}

/** One row of `sesion ver`: registry identity + liveness. */
export interface SessionAgentView {
  id: string;
  name: string;
  provider?: string;
  role?: string;
  cwd?: string;
  live: boolean;
  pid?: number;
}

export type SessionReaderFn = () =>
  | { agents: SessionAgentView[] }
  | Promise<{ agents: SessionAgentView[] }>;

/**
 * Join registry identity with PTY liveness. Pure: `pty-<id>` links a live PTY
 * to its agent (the convention AddAgentModal establishes); PTYs with no
 * registry entry (orphans, pre-registry spawns) show as live unknowns rather
 * than vanishing. NOTE: no `model` column — models live renderer-side (store
 * + spawn args), not in the registry; M6 handles model selection at build.
 */
export function buildSessionView(
  ptyList: PtyView[],
  registryAgents: Record<string, RegistryAgentView>
): SessionAgentView[] {
  const out: SessionAgentView[] = [];
  for (const [id, meta] of Object.entries(registryAgents)) {
    // Live PTYs use `pty-<id>` (UI hires) or, for restored/ephemeral workers,
    // the agent id itself — match either, never drop.
    const live = ptyList.find((p) => p.id === `pty-${id}` || p.id === id);
    out.push({
      id,
      name: meta.name ?? id,
      provider: meta.provider,
      role: meta.role,
      cwd: meta.cwd,
      live: !!live,
      pid: live?.pid,
    });
  }
  for (const p of ptyList) {
    const known = Object.keys(registryAgents).some((id) => `pty-${id}` === p.id || id === p.id);
    // Keys always present (undefined, never absent): the JSON wire format is
    // identical either way, but explicit shape keeps deepEqual/tests honest.
    if (!known) out.push({ id: p.id, name: p.id, provider: undefined, role: undefined, cwd: p.cwd, live: true, pid: p.pid });
  }
  return out;
}

/** User-facing agent description (CLI `sesion armar`) → spawn opts. Pure. */
export interface AgentSpec {
  name?: unknown;
  cwd?: unknown;
  command?: unknown;
  provider?: unknown;
  role?: unknown;
  capabilities?: unknown;
  isolate?: unknown;
}

/** Validate exactly like the UI hire path (name/cwd/command required). Pure. */
export function validateAgentSpec(spec: AgentSpec): { ok: true } | { ok: false; error: string } {
  if (!spec || typeof spec !== 'object') return { ok: false, error: 'spec inválida' };
  if (typeof spec.name !== 'string' || !spec.name.trim()) return { ok: false, error: 'falta el nombre del agente' };
  if (typeof spec.cwd !== 'string' || !spec.cwd.trim()) return { ok: false, error: 'falta la carpeta de trabajo (cwd)' };
  if (typeof spec.command !== 'string' || !spec.command.trim()) return { ok: false, error: 'falta el comando (p. ej. "claude --model opus")' };
  if (spec.provider !== undefined && (typeof spec.provider !== 'string' || !spec.provider.trim())) {
    return { ok: false, error: 'proveedor inválido' };
  }
  if (spec.role !== undefined && typeof spec.role !== 'string') return { ok: false, error: 'rol inválido' };
  if (spec.capabilities !== undefined &&
    (!Array.isArray(spec.capabilities) || spec.capabilities.some((c) => typeof c !== 'string'))) {
    return { ok: false, error: 'capabilities debe ser lista de strings' };
  }
  return { ok: true };
}

/** Agent id scheme, mirroring AddAgentModal.uniqueId (slug + timestamp). Pure. */
export function uniqueAgentId(name: string): string {
  return `${name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'agent'}-${Date.now().toString(36)}`;
}

/** Build spawn opts from a validated spec. Pure (tokenizeCommand is shared). */
export function buildChannelSpawnOpts(spec: {
  name: string; cwd: string; command: string; provider?: string;
  role?: string; capabilities?: string[]; isolate?: boolean;
}): { ptyId: string; id: string; opts: ChannelSpawnOpts } {
  const id = uniqueAgentId(spec.name);
  const ptyId = `pty-${id}`;
  const [exe, ...args] = tokenizeCommand(spec.command.trim());
  return {
    id,
    ptyId,
    opts: {
      id: ptyId,
      cwd: spec.cwd,
      command: exe,
      provider: spec.provider,
      args,
      cols: 100,
      rows: 30,
      isolate: spec.isolate,
      hive: {
        id,
        name: spec.name.trim(),
        provider: spec.provider,
        cwd: spec.cwd,
        role: spec.role?.trim() || undefined,
        capabilities: spec.capabilities
      }
    }
  };
}

function isLoopback(addr: string): boolean {
  const a = addr.replace(/^::ffff:/, '');
  return a === '::1' || a.startsWith('127.');
}

function json(res: ServerResponse, status: number, body: unknown): void {
  const text = JSON.stringify(body);
  res.writeHead(status, { 'content-type': 'application/json', 'content-length': Buffer.byteLength(text) });
  res.end(text);
}

/** Max JSON body we will buffer (mirrors the broker's payload cap idea). */
const MAX_JSON_BODY = 65536;

function readJsonBody(req: IncomingMessage): Promise<{ ok: true; value: unknown } | { ok: false; error: string }> {
  return new Promise((resolve) => {
    const chunks: Buffer[] = [];
    let size = 0;
    let done = false;
    const fail = (error: string): void => {
      if (done) return;
      done = true;
      resolve({ ok: false, error });
    };
    req.on('data', (c: Buffer) => {
      size += c.length;
      if (size > MAX_JSON_BODY) {
        fail('payload_too_large');
        try { req.destroy(); } catch { /* noop */ }
        return;
      }
      chunks.push(c);
    });
    req.on('end', () => {
      if (done) return;
      done = true;
      try {
        resolve({ ok: true, value: JSON.parse(Buffer.concat(chunks).toString('utf8')) });
      } catch {
        resolve({ ok: false, error: 'invalid_json' });
      }
    });
    req.on('error', () => fail('body_error'));
  });
}

export class ControlChannel {
  private server: Server | null = null;
  private readonly token: string;
  private readonly spawn?: ChannelSpawnFn;
  private readonly kill?: ChannelKillFn;
  private readonly repaint?: () => number;
  private readonly read?: SessionReaderFn;
  private readonly packs?: ControlChannelOptions['packs'];
  private readonly importPack?: ControlChannelOptions['importPack'];
  private readonly brief?: ControlChannelOptions['brief'];
  private readonly about?: ControlChannelOptions['about'];

  constructor(opts: ControlChannelOptions) {
    this.about = opts.about;
    this.packs = opts.packs;
    this.importPack = opts.importPack;
    this.brief = opts.brief;
    this.token = opts.token;
    this.spawn = opts.spawn;
    this.kill = opts.kill;
    this.repaint = opts.repaint;
    this.read = opts.read;
  }

  /** Bind a loopback port (0 ⇒ OS-assigned). Resolves the actual bound port. */
  start(preferredPort = 0): Promise<{ ok: boolean; port?: number; error?: string }> {
    return new Promise((resolve) => {
      if (this.server) { resolve({ ok: false, error: 'already running' }); return; }
      const server = createServer((req, res) => {
        void this.handle(req, res).catch(() => {
          try { json(res, 500, { ok: false, error: 'internal' }); } catch { /* socket gone */ }
        });
      });
      const onError = (e: Error): void => {
        server.off('listening', onListening);
        resolve({ ok: false, error: e instanceof Error ? e.message : String(e) });
      };
      const onListening = (): void => {
        server.off('error', onError);
        this.server = server;
        const addr = server.address();
        resolve({ ok: true, port: addr && typeof addr === 'object' ? addr.port : preferredPort });
      };
      server.once('error', onError);
      server.once('listening', onListening);
      // '127.0.0.1' ONLY — never tunneled, never public. The token is a second
      // layer, not the boundary: a non-loopback peer is refused before auth.
      server.listen(preferredPort, '127.0.0.1');
    });
  }

  /** Close the endpoint. Idempotent and best-effort. */
  stop(): void {
    try { this.server?.close(); } catch { /* noop */ }
    this.server = null;
  }

  /** Bound port, or null when stopped. For logs only — callers read the file. */
  port(): number | null {
    if (!this.server) return null;
    const addr = this.server.address();
    return addr && typeof addr === 'object' ? addr.port : null;
  }

  private authorized(req: IncomingMessage): boolean {
    const header = req.headers.authorization ?? '';
    return header === `Bearer ${this.token}`;
  }

  private async handle(req: IncomingMessage, res: ServerResponse): Promise<void> {
    // Defense in depth: even bound loopback-only, refuse any non-loopback peer.
    if (!isLoopback(req.socket.remoteAddress ?? '')) {
      json(res, 403, { ok: false, error: 'loopback only' });
      return;
    }
    const path = (req.url ?? '').split('?')[0];
    if (req.method === 'GET' && path === '/salud') {
      if (!this.authorized(req)) {
        json(res, 401, { ok: false, error: 'unauthorized' });
        return;
      }
      let instance: InstanceInfo | undefined;
      try { instance = this.about?.(); } catch { instance = undefined; }
      json(res, 200, instance ? { ok: true, service: 'munder-control', instance } : { ok: true, service: 'munder-control' });
      return;
    }
    if (req.method === 'GET' && path === '/sesion') {
      if (!this.authorized(req)) {
        json(res, 401, { ok: false, error: 'unauthorized' });
        return;
      }
      if (!this.read) {
        json(res, 501, { ok: false, error: 'lectura no disponible en este build' });
        return;
      }
      try {
        const snap = await this.read();
        const agents = Array.isArray(snap?.agents) ? snap.agents : [];
        json(res, 200, { ok: true, agents, count: agents.length });
      } catch (e: unknown) {
        json(res, 500, { ok: false, error: e instanceof Error ? e.message : String(e) });
      }
      return;
    }
    if (req.method === 'GET' && path === '/packs') {
      if (!this.authorized(req)) {
        json(res, 401, { ok: false, error: 'unauthorized' });
        return;
      }
      if (!this.packs) {
        json(res, 501, { ok: false, error: 'packs no disponibles en este build' });
        return;
      }
      json(res, 200, { ok: true, packs: this.packs().packs.map(summarizePack) });
      return;
    }
    if (req.method === 'POST' && path === '/sesion/pack') {
      if (!this.authorized(req)) {
        json(res, 401, { ok: false, error: 'unauthorized' });
        return;
      }
      await this.handlePackSession(req, res);
      return;
    }
    if ((req.method === 'POST' && path === '/sesion/agentes') ||
        (req.method === 'DELETE' && path.startsWith('/sesion/agentes/'))) {
      if (!this.authorized(req)) {
        json(res, 401, { ok: false, error: 'unauthorized' });
        return;
      }
      void this.handleMutation(req, res, path).catch((e: unknown) => {
        json(res, 500, { ok: false, error: e instanceof Error ? e.message : String(e) });
      });
      return;
    }
    if (req.method === 'POST' && path === '/repaint') {
      if (!this.authorized(req)) {
        json(res, 401, { ok: false, error: 'unauthorized' });
        return;
      }
      if (!this.repaint) {
        json(res, 501, { ok: false, error: 'repaint no disponible en este build' });
        return;
      }
      try {
        const windows = this.repaint();
        json(res, 200, { ok: true, windows });
      } catch (e: unknown) {
        json(res, 500, { ok: false, error: e instanceof Error ? e.message : String(e) });
      }
      return;
    }
    json(res, 404, { ok: false, error: 'not found' });
  }

  /** Start the chosen agents of a pack, one at a time, then brief each one. */
  private async handlePackSession(req: IncomingMessage, res: ServerResponse): Promise<void> {
    if (!this.spawn || !this.packs) {
      json(res, 501, { ok: false, error: 'packs no disponibles en este build' });
      return;
    }
    const body = await readJsonBody(req);
    if (!body.ok) {
      json(res, body.error === 'payload_too_large' ? 413 : 400, { ok: false, error: body.error });
      return;
    }
    const plan = planPackSession((body.value ?? {}) as PackSessionRequest, { packs: this.packs, importPack: this.importPack });
    if (!plan.ok) {
      json(res, 400, { ok: false, error: plan.error });
      return;
    }
    const agents: Array<{ id?: string; name: string; ok: boolean; error?: string }> = [];
    for (const def of plan.agents) {
      const name = packAgentName(def);
      const built = buildChannelSpawnOpts({
        name, cwd: plan.cwd, command: plan.command, provider: plan.provider,
        role: def.role, capabilities: def.does
      });
      const r = await this.spawn(built.opts);
      if (!r.ok) {
        agents.push({ name, ok: false, error: r.error ?? 'spawn failed' });
        continue;
      }
      try {
        this.brief?.(built.id, `${def.role}: your job`, packBrief(def, { displayName: plan.pack.displayName, imported: plan.imported }));
      } catch { /* the agent is live; the brief is best effort */ }
      agents.push({ id: built.id, name, ok: true });
    }
    json(res, 200, { ok: agents.every((a) => a.ok), pack: plan.pack.businessType, imported: plan.imported, agents });
  }

  private async handleMutation(req: IncomingMessage, res: ServerResponse, path: string): Promise<void> {
    if (req.method === 'POST') {
      if (!this.spawn) {
        json(res, 501, { ok: false, error: 'spawn no disponible en este build' });
        return;
      }
      const body = await readJsonBody(req);
      if (!body.ok) {
        json(res, body.error === 'payload_too_large' ? 413 : 400, { ok: false, error: body.error });
        return;
      }
      const spec = (body.value ?? {}) as AgentSpec;
      const valid = validateAgentSpec(spec);
      if (!valid.ok) {
        json(res, 400, { ok: false, error: valid.error });
        return;
      }
      const v = spec as { name: string; cwd: string; command: string; provider?: string; role?: string; capabilities?: string[]; isolate?: boolean };
      const built = buildChannelSpawnOpts({
        name: v.name, cwd: v.cwd, command: v.command, provider: v.provider,
        role: v.role, capabilities: v.capabilities, isolate: v.isolate
      });
      const r = await this.spawn(built.opts);
      if (!r.ok) {
        // Same contract as pty:spawn: accepted-but-failed rides 200 + ok:false.
        json(res, 200, { ok: false, error: r.error ?? 'spawn failed' });
        return;
      }
      json(res, 200, {
        ok: true, id: built.id, ptyId: built.ptyId,
        cwd: r.cwd, worktreePath: r.worktreePath, provider: v.provider
      });
      return;
    }
    // DELETE /sesion/agentes/:id
    if (!this.kill) {
      json(res, 501, { ok: false, error: 'kill no disponible en este build' });
      return;
    }
    const id = decodeURIComponent(path.slice('/sesion/agentes/'.length)).trim();
    if (!id || id.includes('/')) {
      json(res, 400, { ok: false, error: 'id inválido' });
      return;
    }
    const r = await this.kill(id);
    if (!r.ok) {
      json(res, 404, { ok: false, error: r.error ?? 'no existe' });
      return;
    }
    json(res, 200, { ok: true, id });
  }
}
